### ISSUE TITLE
Unknown block '"weather"' for key '`block`

### ISSUE THREAD

**Issue by farwayer** [MaxVerevkin/swaystatus#12]
After updating to the master

**Comment by MaxVerevkin** [comment]
I haven't ported it to the new formatting (#11) because the block itself is incomplete so I wanted to make it i3status-rs compatible while changing formatting. I didn't have the time to revisit the block, so I enabled it in 620ffa94.

By the way, I suppose you will need to reconfigure the blocks to use the [new formatting](https://maxverevkin.github.io/swaystatus/docs/swaystatus/formatting/index.html). If you have any feedback on the ergonomics, please share.

**Comment by farwayer** [comment]
Now it works thanks! PR with default format fix https://github.com/MaxVerevkin/swaystatus/pull/13

**Comment by MaxVerevkin** [comment]
Now weather block should more usable: `autolocate` is not always on, `wind` and `wind_kmh` are distinct, temperature/humidity has a unit and thus includes the degree/percent symbol, the block doesn't error when there's not internet, `lang` option is now presented.
